### ISSUE TITLE
Bouncing variable doesn't bounce

### ISSUE THREAD

**Issue by NSheeran** [cdaein/mica-gd405-sp17#1]
Hi all,

I'm trying to have the bezier that runs up the stem of the f to bounce back down, and keep going back and forth. Here's the code running that bezier:

var bendY = 164; [globally defined]
var ySpeed = mouseY/100; [defined in draw]
    
    if (bendY < 120) { 
    bendY = bendY + ySpeed; 
    } 

I get the issue, it hits 120, goes to 121, and just keeps going back and forth and looks like it's stopped. I just have no idea how to handle it, I've tried copying a few bouncing ball tutorials and appropriating but that hasn't worked either.

**Comment by NSheeran** [comment]
Oh, here's an example:

http://codepen.io/nsheeran/pen/apXObg

**Comment by cdaein** [comment]
That's because your current if conditional will make your `bendY` stuck at `120`.
You need another variable to control the *direction*. 
Instead of directly affecting `bendY`, change the `direction` variable.


```js
var ySpeed;
var direction = 1;

function draw() {
    background(255);
    
    fill(0, 200, bendY);
    
    ySpeed = mouseY/100;

//    creates loop in bezier anchors with y arguments
    bendY = bendY - ySpeed * direction;
    
    if (bendY < 120 || bendY > mouseY) { 
      direction *= -1;
    }

  // more stuff below.....
}
```

**Comment by NSheeran** [comment]
I updated this code and ran into the same problem that most other expected solutions had, now the bezier just keeps going up forever once the mouse moves.

http://codepen.io/nsheeran/pen/apXObg

**Comment by cdaein** [comment]
If you look at my code above,

```js
var ySpeed;
var direction = 1;
```
... are set to be *global variables*. Place them outside of `draw()`. Otherwise, it will keep being overridden every frame to default values.

**Comment by NSheeran** [comment]
I understand now! var yspeed; had to be set with no defined value globally then written again in draw. I kept switching it in and out of draw. Thank you!
