### ISSUE TITLE
All scenes run at once as events

### ISSUE THREAD

**Issue by NSheeran** [cdaein/mica-gd405-sp17#2]
I'm trying to create two scenes in my type specimen -- one is the alphabet from before, and the other is a typing application. I've separated each into scenes, and started with the typing scene, but after pressing left or right arrows to switch, they both run at once. The alphabet is also static, and only adds frames when a key is pressed. 

It seems like keyTyped is running all the time? Even when I start the scene on the alphabet, typing reveals letters. 

Maybe I need to house keyTyped in another function?

Here's the link:
http://codepen.io/nsheeran/pen/ryVqdE

**Comment by cdaein** [comment]
Nick,
it would be best that you simplify the code to get help. Recreate the problem in its simplest form. That way, it will also be easy for me to take a look.

**Comment by NSheeran** [comment]
Code has been refined slightly but I'm not sure what to remove before I exclude whatever is causing the problem. 

I've also defined sceneCount as 1 and turned on keyPressed (which should allow arrow keys to switch scenes). This seems to have allowed alphabet (the function containing what I presented last week) to run, but it doesn't appear until a key is typed.

Maybe it seems like the sceneCount conditionals set within the keyPressed function aren't working, and causing both alphabet() and keyTyped() to fire at once.

http://codepen.io/nsheeran/pen/ryVqdE

**Comment by NSheeran** [comment]
If this isn't helping, and you are available, maybe we could talk briefly via Skype/Google?

**Comment by cdaein** [comment]
I can't do skype now. If you don't know how to simplify the code, then, start a new sketch, just focus on getting the scenes working. you don't need 26 letters or all the color changing code, etc. just focus on making the scenes work with, say, 2 letters. 

I will check your progress again sometime tonight.

**Comment by NSheeran** [comment]
Here is a simplified code. It does look like both functions are being called regardless of scene. Isn't there a command to turn off or disable a function? Cannot find if so.

http://codepen.io/nsheeran/pen/ryVqdE

**Comment by cdaein** [comment]
You don't want to call `keyPressed()` or `keyTyped()` yourself - they are *callback* functions and they will be automatically called when key typing event happens. 

This examples should solve your problem. Pay attention to the flow of the program.

```js
var xpos = 50;
var ypos = 50;
var sceneCount = 1;

function setup() {
  createCanvas(600, 400);
  background(200);
}

function draw() {
  if (sceneCount == 2) {
    alphabet();
  }
}

function letterA(x, y) {
  push();
  translate(x, y);
  beginShape();
  vertex(20, 0);
  vertex(40, 40);
  vertex(0, 40);
  endShape(CLOSE);
  pop();
}

function alphabet() {
  background(100);
  letterA(width/2 + sin(frameCount/50)*100, height/2);
}

function keyTyped() {
  if (sceneCount == 1) {
    letterA(xpos, ypos);
    xpos += 50;
    if (xpos > width - 100) {
      xpos = 50;
      ypos += 50;
    }
  }
}

function keyPressed() {
  if (keyCode == LEFT_ARROW) {
    sceneCount = 1;
    background(200);
    xpos = 50;
    ypos = 50;
  } else if (keyCode == RIGHT_ARROW) {
    sceneCount = 2;
    background(100);
  }
}
```

**Comment by NSheeran** [comment]
This does it, and I understand what needs to change. Thank you
